# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Max.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(494, 413)
        MainWindow.setMaximumSize(QtCore.QSize(556, 413))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.VerticalLayout_2 = QtWidgets.QVBoxLayout()
        self.VerticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.VerticalLayout_2.setObjectName("VerticalLayout_2")
        self.RXLNAGain_TopLabel = QtWidgets.QLabel(self.centralwidget)
        self.RXLNAGain_TopLabel.setMaximumSize(QtCore.QSize(100, 15))
        self.RXLNAGain_TopLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.RXLNAGain_TopLabel.setObjectName("RXLNAGain_TopLabel")
        self.VerticalLayout_2.addWidget(self.RXLNAGain_TopLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.RXLNAGain_ComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.RXLNAGain_ComboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.RXLNAGain_ComboBox.setEditable(False)
        self.RXLNAGain_ComboBox.setObjectName("RXLNAGain_ComboBox")
        self.RXLNAGain_ComboBox.addItem("")
        self.RXLNAGain_ComboBox.addItem("")
        self.RXLNAGain_ComboBox.addItem("")
        self.VerticalLayout_2.addWidget(self.RXLNAGain_ComboBox)
        self.RXVGAGain_TopLabel = QtWidgets.QLabel(self.centralwidget)
        self.RXVGAGain_TopLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.RXVGAGain_TopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RXVGAGain_TopLabel.setOpenExternalLinks(False)
        self.RXVGAGain_TopLabel.setObjectName("RXVGAGain_TopLabel")
        self.VerticalLayout_2.addWidget(self.RXVGAGain_TopLabel)
        self.RXVGAGain_Line = QtWidgets.QLineEdit(self.centralwidget)
        self.RXVGAGain_Line.setMaximumSize(QtCore.QSize(16777215, 20))
        self.RXVGAGain_Line.setObjectName("RXVGAGain_Line")
        self.VerticalLayout_2.addWidget(self.RXVGAGain_Line)
        self.RXVGAGain_ScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.RXVGAGain_ScrollBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.RXVGAGain_ScrollBar.setMaximum(31)
        self.RXVGAGain_ScrollBar.setInvertedControls(False)
        self.RXVGAGain_ScrollBar.setPageStep(1)
        self.RXVGAGain_ScrollBar.setSingleStep(1)
        self.RXVGAGain_ScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.RXVGAGain_ScrollBar.setObjectName("RXVGAGain_ScrollBar")
        self.VerticalLayout_2.addWidget(self.RXVGAGain_ScrollBar)
        self.TXVGAGain_TopLabel = QtWidgets.QLabel(self.centralwidget)
        self.TXVGAGain_TopLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.TXVGAGain_TopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TXVGAGain_TopLabel.setObjectName("TXVGAGain_TopLabel")
        self.VerticalLayout_2.addWidget(self.TXVGAGain_TopLabel)
        self.TXVGAGain_Line = QtWidgets.QLineEdit(self.centralwidget)
        self.TXVGAGain_Line.setMaximumSize(QtCore.QSize(16777215, 20))
        self.TXVGAGain_Line.setObjectName("TXVGAGain_Line")
        self.VerticalLayout_2.addWidget(self.TXVGAGain_Line)
        self.TXVGAGain_ScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.TXVGAGain_ScrollBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.TXVGAGain_ScrollBar.setMaximum(63)
        self.TXVGAGain_ScrollBar.setInvertedControls(False)
        self.TXVGAGain_ScrollBar.setPageStep(1)
        self.TXVGAGain_ScrollBar.setSingleStep(1)
        self.TXVGAGain_ScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.TXVGAGain_ScrollBar.setObjectName("TXVGAGain_ScrollBar")
        self.VerticalLayout_2.addWidget(self.TXVGAGain_ScrollBar)
        self.TXBasebandGain_TopLabel = QtWidgets.QLabel(self.centralwidget)
        self.TXBasebandGain_TopLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.TXBasebandGain_TopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TXBasebandGain_TopLabel.setObjectName("TXBasebandGain_TopLabel")
        self.VerticalLayout_2.addWidget(self.TXBasebandGain_TopLabel)
        self.TXBasebandGain_Layout = QtWidgets.QHBoxLayout()
        self.TXBasebandGain_Layout.setObjectName("TXBasebandGain_Layout")
        self.TXBasebandGain_ComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.TXBasebandGain_ComboBox.setMaximumSize(QtCore.QSize(16777215, 20))
        self.TXBasebandGain_ComboBox.setEditable(False)
        self.TXBasebandGain_ComboBox.setObjectName("TXBasebandGain_ComboBox")
        self.TXBasebandGain_ComboBox.addItem("")
        self.TXBasebandGain_ComboBox.addItem("")
        self.TXBasebandGain_Layout.addWidget(self.TXBasebandGain_ComboBox)
        self.TXBasebandGain_Label = QtWidgets.QLabel(self.centralwidget)
        self.TXBasebandGain_Label.setObjectName("TXBasebandGain_Label")
        self.TXBasebandGain_Layout.addWidget(self.TXBasebandGain_Label)
        self.VerticalLayout_2.addLayout(self.TXBasebandGain_Layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.VerticalLayout_2.addItem(spacerItem)
        self.SendAll_Button = QtWidgets.QPushButton(self.centralwidget)
        self.SendAll_Button.setMaximumSize(QtCore.QSize(16777215, 23))
        self.SendAll_Button.setToolTip("")
        self.SendAll_Button.setObjectName("SendAll_Button")
        self.VerticalLayout_2.addWidget(self.SendAll_Button)
        self.gridLayout.addLayout(self.VerticalLayout_2, 5, 2, 2, 1)
        self.TopSide_HorizontalLayout = QtWidgets.QHBoxLayout()
        self.TopSide_HorizontalLayout.setObjectName("TopSide_HorizontalLayout")
        self.Setups_Label = QtWidgets.QLabel(self.centralwidget)
        self.Setups_Label.setObjectName("Setups_Label")
        self.TopSide_HorizontalLayout.addWidget(self.Setups_Label)
        self.Setups_ComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Setups_ComboBox.setMinimumSize(QtCore.QSize(100, 23))
        self.Setups_ComboBox.setMaximumSize(QtCore.QSize(300, 23))
        self.Setups_ComboBox.setEditable(True)
        self.Setups_ComboBox.setObjectName("Setups_ComboBox")
        self.Setups_ComboBox.addItem("")
        self.Setups_ComboBox.setItemText(0, "")
        self.Setups_ComboBox.addItem("")
        self.Setups_ComboBox.addItem("")
        self.TopSide_HorizontalLayout.addWidget(self.Setups_ComboBox)
        self.Del_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Del_Button.setMinimumSize(QtCore.QSize(0, 0))
        self.Del_Button.setMaximumSize(QtCore.QSize(30, 23))
        self.Del_Button.setCheckable(False)
        self.Del_Button.setAutoDefault(False)
        self.Del_Button.setObjectName("Del_Button")
        self.TopSide_HorizontalLayout.addWidget(self.Del_Button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TopSide_HorizontalLayout.addItem(spacerItem1)
        self.ConnectionStatus_Label = QtWidgets.QLabel(self.centralwidget)
        self.ConnectionStatus_Label.setObjectName("ConnectionStatus_Label")
        self.TopSide_HorizontalLayout.addWidget(self.ConnectionStatus_Label)
        self.ConnectionGraphic = QtWidgets.QGraphicsView(self.centralwidget)
        self.ConnectionGraphic.setMaximumSize(QtCore.QSize(13, 13))
        self.ConnectionGraphic.setAutoFillBackground(True)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.ConnectionGraphic.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.ConnectionGraphic.setForegroundBrush(brush)
        self.ConnectionGraphic.setObjectName("ConnectionGraphic")
        self.TopSide_HorizontalLayout.addWidget(self.ConnectionGraphic)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TopSide_HorizontalLayout.addItem(spacerItem2)
        self.Lock_Label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.Lock_Label.setFont(font)
        self.Lock_Label.setTextFormat(QtCore.Qt.AutoText)
        self.Lock_Label.setObjectName("Lock_Label")
        self.TopSide_HorizontalLayout.addWidget(self.Lock_Label)
        self.Lock_CheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.Lock_CheckBox.setText("")
        self.Lock_CheckBox.setObjectName("Lock_CheckBox")
        self.TopSide_HorizontalLayout.addWidget(self.Lock_CheckBox)
        self.gridLayout.addLayout(self.TopSide_HorizontalLayout, 0, 0, 1, 4)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 1, 1, 3)
        self.VerticalLayout_1 = QtWidgets.QVBoxLayout()
        self.VerticalLayout_1.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.VerticalLayout_1.setObjectName("VerticalLayout_1")
        self.RFFrequency_TopLabel = QtWidgets.QLabel(self.centralwidget)
        self.RFFrequency_TopLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.RFFrequency_TopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RFFrequency_TopLabel.setOpenExternalLinks(False)
        self.RFFrequency_TopLabel.setObjectName("RFFrequency_TopLabel")
        self.VerticalLayout_1.addWidget(self.RFFrequency_TopLabel)
        self.RFFrequency_Layout = QtWidgets.QHBoxLayout()
        self.RFFrequency_Layout.setObjectName("RFFrequency_Layout")
        self.RFFrequency_Line = QtWidgets.QLineEdit(self.centralwidget)
        self.RFFrequency_Line.setMaximumSize(QtCore.QSize(100, 20))
        self.RFFrequency_Line.setObjectName("RFFrequency_Line")
        self.RFFrequency_Layout.addWidget(self.RFFrequency_Line)
        self.RFFrequency_Label = QtWidgets.QLabel(self.centralwidget)
        self.RFFrequency_Label.setObjectName("RFFrequency_Label")
        self.RFFrequency_Layout.addWidget(self.RFFrequency_Label)
        self.VerticalLayout_1.addLayout(self.RFFrequency_Layout)
        self.RFFrequency_ScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.RFFrequency_ScrollBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.RFFrequency_ScrollBar.setMinimum(4900)
        self.RFFrequency_ScrollBar.setMaximum(5900)
        self.RFFrequency_ScrollBar.setPageStep(1)
        self.RFFrequency_ScrollBar.setSingleStep(1)
        self.RFFrequency_ScrollBar.setInvertedControls(False)
        self.RFFrequency_ScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.RFFrequency_ScrollBar.setObjectName("RFFrequency_ScrollBar")
        self.VerticalLayout_1.addWidget(self.RFFrequency_ScrollBar)
        self.PADACOutputBias_TopLabel = QtWidgets.QLabel(self.centralwidget)
        self.PADACOutputBias_TopLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.PADACOutputBias_TopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PADACOutputBias_TopLabel.setObjectName("PADACOutputBias_TopLabel")
        self.VerticalLayout_1.addWidget(self.PADACOutputBias_TopLabel)
        self.PADACOutputBias_Layout = QtWidgets.QHBoxLayout()
        self.PADACOutputBias_Layout.setObjectName("PADACOutputBias_Layout")
        self.PADACOutputBias_Line = QtWidgets.QLineEdit(self.centralwidget)
        self.PADACOutputBias_Line.setMaximumSize(QtCore.QSize(100, 20))
        self.PADACOutputBias_Line.setObjectName("PADACOutputBias_Line")
        self.PADACOutputBias_Layout.addWidget(self.PADACOutputBias_Line)
        self.PADACOutputBias_Label = QtWidgets.QLabel(self.centralwidget)
        self.PADACOutputBias_Label.setObjectName("PADACOutputBias_Label")
        self.PADACOutputBias_Layout.addWidget(self.PADACOutputBias_Label)
        self.VerticalLayout_1.addLayout(self.PADACOutputBias_Layout)
        self.PADACOutputBias_ScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.PADACOutputBias_ScrollBar.setMaximumSize(QtCore.QSize(16777215, 20))
        self.PADACOutputBias_ScrollBar.setMaximum(315)
        self.PADACOutputBias_ScrollBar.setInvertedControls(False)
        self.PADACOutputBias_ScrollBar.setPageStep(1)
        self.PADACOutputBias_ScrollBar.setSingleStep(1)
        self.PADACOutputBias_ScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.PADACOutputBias_ScrollBar.setObjectName("PADACOutputBias_ScrollBar")
        self.VerticalLayout_1.addWidget(self.PADACOutputBias_ScrollBar)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.VerticalLayout_1.addWidget(self.line_2)
        self.Max2828_TopLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Max2828_TopLabel.setFont(font)
        self.Max2828_TopLabel.setObjectName("Max2828_TopLabel")
        self.VerticalLayout_1.addWidget(self.Max2828_TopLabel, 0, QtCore.Qt.AlignHCenter)
        self.Max2828_ComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Max2828_ComboBox.setObjectName("Max2828_ComboBox")
        self.Max2828_ComboBox.addItem("")
        self.Max2828_ComboBox.addItem("")
        self.Max2828_ComboBox.addItem("")
        self.Max2828_ComboBox.addItem("")
        self.VerticalLayout_1.addWidget(self.Max2828_ComboBox)
        self.Max5866_TopLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.Max5866_TopLabel.setFont(font)
        self.Max5866_TopLabel.setObjectName("Max5866_TopLabel")
        self.VerticalLayout_1.addWidget(self.Max5866_TopLabel, 0, QtCore.Qt.AlignHCenter)
        self.Max5866_ComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Max5866_ComboBox.setEditable(False)
        self.Max5866_ComboBox.setObjectName("Max5866_ComboBox")
        self.Max5866_ComboBox.addItem("")
        self.Max5866_ComboBox.addItem("")
        self.Max5866_ComboBox.addItem("")
        self.Max5866_ComboBox.addItem("")
        self.Max5866_ComboBox.addItem("")
        self.VerticalLayout_1.addWidget(self.Max5866_ComboBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.VerticalLayout_1.addItem(spacerItem3)
        self.gridLayout.addLayout(self.VerticalLayout_1, 5, 1, 2, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 7, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 21))
        self.menubar.setObjectName("menubar")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLPT_Port_Configurate = QtWidgets.QAction(MainWindow)
        self.actionLPT_Port_Configurate.setCheckable(True)
        self.actionLPT_Port_Configurate.setObjectName("actionLPT_Port_Configurate")
        self.actionAuto_Send_to_Register = QtWidgets.QAction(MainWindow)
        self.actionAuto_Send_to_Register.setCheckable(True)
        self.actionAuto_Send_to_Register.setChecked(True)
        self.actionAuto_Send_to_Register.setObjectName("actionAuto_Send_to_Register")
        self.actionClock_PulseWidth_Value = QtWidgets.QAction(MainWindow)
        self.actionClock_PulseWidth_Value.setCheckable(True)
        self.actionClock_PulseWidth_Value.setObjectName("actionClock_PulseWidth_Value")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuExit.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionLPT_Port_Configurate)
        self.menuOptions.addAction(self.actionAuto_Send_to_Register)
        self.menuOptions.addAction(self.actionClock_PulseWidth_Value)
        self.menubar.addAction(self.menuExit.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.LineEditName = QtWidgets.QLineEdit()##
        self.ScrollBarName = QtWidgets.QScrollBar()##

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Programming-Control Interface v1.0"))
        self.RXLNAGain_TopLabel.setText(_translate("MainWindow", "RX LNA Gain"))
        self.RXLNAGain_ComboBox.setItemText(0, _translate("MainWindow", "Min"))
        self.RXLNAGain_ComboBox.setItemText(1, _translate("MainWindow", "Mid"))
        self.RXLNAGain_ComboBox.setItemText(2, _translate("MainWindow", "Max"))
        self.RXVGAGain_TopLabel.setText(_translate("MainWindow", "RX VGA Gain"))
        self.RXVGAGain_Line.setText(_translate("MainWindow", "0"))
        self.RXVGAGain_ScrollBar.setStatusTip(_translate("MainWindow", "Change to RX VGA Gain"))
        self.TXVGAGain_TopLabel.setText(_translate("MainWindow", "TX VGA Gain"))
        self.TXVGAGain_Line.setText(_translate("MainWindow", "0"))
        self.TXVGAGain_ScrollBar.setStatusTip(_translate("MainWindow", "Change to TX VGA Gain"))
        self.TXBasebandGain_TopLabel.setText(_translate("MainWindow", "TX Baseband Gain"))
        self.TXBasebandGain_ComboBox.setItemText(0, _translate("MainWindow", "-5.0"))
        self.TXBasebandGain_ComboBox.setItemText(1, _translate("MainWindow", "Max Gain"))
        self.TXBasebandGain_Label.setText(_translate("MainWindow", "dB"))
        self.SendAll_Button.setStatusTip(_translate("MainWindow", "It sends bytes"))
        self.SendAll_Button.setText(_translate("MainWindow", "Send All"))
        self.Setups_Label.setText(_translate("MainWindow", "Setups: "))
        self.Setups_ComboBox.setItemText(1, _translate("MainWindow", "Evaluation Defaults"))
        self.Setups_ComboBox.setItemText(2, _translate("MainWindow", "LastPowerDown"))
        self.Del_Button.setStatusTip(_translate("MainWindow", "Delete"))
        self.Del_Button.setText(_translate("MainWindow", "Del"))
        self.ConnectionStatus_Label.setStatusTip(_translate("MainWindow", "Connection Status"))
        self.ConnectionStatus_Label.setText(_translate("MainWindow", "Connection Status:"))
        self.ConnectionGraphic.setStatusTip(_translate("MainWindow", "Connection"))
        self.Lock_Label.setStatusTip(_translate("MainWindow", "Lock"))
        self.Lock_Label.setText(_translate("MainWindow", "Lock: "))
        self.Lock_CheckBox.setStatusTip(_translate("MainWindow", "Lock"))
        self.RFFrequency_TopLabel.setText(_translate("MainWindow", "RF Frequency"))
        self.RFFrequency_Line.setText(_translate("MainWindow", "0"))
        self.RFFrequency_Label.setText(_translate("MainWindow", "Mhz"))
        self.RFFrequency_ScrollBar.setStatusTip(_translate("MainWindow", "Change to RF Frequency"))
        self.PADACOutputBias_TopLabel.setText(_translate("MainWindow", "PA DAC Output Bias"))
        self.PADACOutputBias_Line.setText(_translate("MainWindow", "0"))
        self.PADACOutputBias_Label.setText(_translate("MainWindow", "uA"))
        self.PADACOutputBias_ScrollBar.setStatusTip(_translate("MainWindow", "Change to PA DAC Output Bias"))
        self.Max2828_TopLabel.setText(_translate("MainWindow", "Max2828"))
        self.Max2828_ComboBox.setStatusTip(_translate("MainWindow", "Change to Max2828 Mode(Default)"))
        self.Max2828_ComboBox.setItemText(0, _translate("MainWindow", "Receiver"))
        self.Max2828_ComboBox.setItemText(1, _translate("MainWindow", "Transmitter"))
        self.Max2828_ComboBox.setItemText(2, _translate("MainWindow", "IDLE"))
        self.Max2828_ComboBox.setItemText(3, _translate("MainWindow", "StandBy"))
        self.Max5866_TopLabel.setText(_translate("MainWindow", "Max5866"))
        self.Max5866_ComboBox.setStatusTip(_translate("MainWindow", "Change to Max5866 Mode"))
        self.Max5866_ComboBox.setItemText(0, _translate("MainWindow", "Shutdown"))
        self.Max5866_ComboBox.setItemText(1, _translate("MainWindow", "IDLE"))
        self.Max5866_ComboBox.setItemText(2, _translate("MainWindow", "RX"))
        self.Max5866_ComboBox.setItemText(3, _translate("MainWindow", "TX"))
        self.Max5866_ComboBox.setItemText(4, _translate("MainWindow", "StandBy"))
        self.menuExit.setTitle(_translate("MainWindow", "Exit"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionLPT_Port_Configurate.setText(_translate("MainWindow", "LPT Port Configure"))
        self.actionAuto_Send_to_Register.setText(_translate("MainWindow", "Auto Send to Register"))
        self.actionClock_PulseWidth_Value.setText(_translate("MainWindow", "Clock PulseWidth Value"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

    def close_application(self):
        app = QtWidgets.QApplication(sys.argv)
        sys.exit(app.exec_())
    def callMain(self):        
        return QtWidgets.QMainWindow()
    def ScrollBarValue(self, ScrollBarName, LineEditName):
        ScrollBar_Value = str(ScrollBarName.value())
        LineEditName.setText(ScrollBar_Value)
    def CheckingLines(self, ScrollBarName, LineEditName):
            if (int(LineEditName.text()) < ScrollBarName.minimum()):
                LineEditName.setText(str(ScrollBarName.minimum()))
                ScrollBarName.setSliderPosition(ScrollBarName.minimum())
                ScrollBarName.setValue(ScrollBarName.minimum())
            elif int(LineEditName.text()) > ScrollBarName.maximum():
                LineEditName.setText(str(ScrollBarName.maximum()))
                ScrollBarName.setSliderPosition(ScrollBarName.maximum())
                ScrollBarName.setValue(ScrollBarName.maximum())
            else:
                pass
       
        
        

"""if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())"""

